services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: pocketpay
      MYSQL_DATABASE: pocketpay
      MYSQL_PASSWORD: 1234
